# Generated by Django 5.2.8 on 2025-11-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('category', models.CharField(choices=[('Drama', 'Drama'), ('Romance', 'Romance'), ('Action', 'Action'), ('Comedy', 'Comedy')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_file', models.FileField(upload_to='videos')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
